### ISSUE TITLE
Model with recursive items cause RecursionError

### ISSUE THREAD

**Issue by danielbradburn** [p1c2u/openapi-core#122]
The SchemaRegistry doesn't handle recursive references, for example the following schema crashes with a ``RecursionError: maximum recursion depth exceeded while calling a Python object`` while trying to parse...

```
    Tree:
      properties:
        children:
          type: array
          items: 
            $ref: '#/components/schemas/Tree'
```

It looks like support was added to handle recursive properties, but recursive array items is currently not supported.

**Comment by phrfpeixoto** [comment]
I've just hit this road block with simple users/groups models:
```yaml
schemas:
  Group:
    type: object
    required:
      - id
      - users
    properties:
      id:
        type: string
        format: uuid
        readOnly: true
      users:
        type: array
        items:
          $ref: '#/components/schemas/User'
  User:
    type: object
    required:
      - id
      - groups
    properties:
      id:
        type: string
        format: uuid
        readOnly: true
      groups:
        type: array
        items:
          $ref: '#/components/schemas/Group'
```
I quickly checked the code and it seems that references are not held. Instead the code dereferences every single **$ref** and replaces it with an instance of `Schema`, so I did not see any practical way of fixing this.
