### ISSUE TITLE
Schemas defined by allOf are not treated as Objects

### ISSUE THREAD

**Issue by phrfpeixoto** [p1c2u/openapi-core#147]
I've noticed that if you define a Schema using _allOf_, that particular schema will note marked as an object itself, even though it's based in other objects.

OAS3 States:

> Composition and Inheritance (Polymorphism)
> 
> The OpenAPI Specification allows combining and extending model definitions using the allOf property of JSON Schema, in effect offering model composition. allOf takes an array of object definitions that are validated independently but together compose a single object.

It's clear that the result of a usage of an _allOf_ statement should produce an object.

Tried with:
```yaml
components:
  schemas:
    Error:
      type: object,
      properties:
        message:
          type: string
    TS:
      type: object
      properties:
        moment:
          type: string,
          format: datetime
    ExtendedError:
      type: object
      properties:
        message:
          type: string
        suberror:
          allOf:
            - $ref: '#/components/schemas/Error'
            - $ref: '#/components/schemas/TS'
```

In this case the `Schema` for `suberror` have it's `type` property set to `SchemaType.Any` because of they way how the type is defined without checking on inheritance:

```python

self.type = SchemaType(schema_type)
# ... REDACTED CODE ...
self.all_of = all_of and list(all_of) or []
```

**Comment by phrfpeixoto** [comment]
As a work around, you may add a type declaration alongside that _allOf_
```yaml
components:
  schemas:
    Error:
      type: object,
      properties:
        message:
          type: string
    TS:
      type: object
      properties:
        moment:
          type: string,
          format: datetime
    ExtendedError:
      type: object
      properties:
        message:
          type: string
        suberror:
          type: object
          allOf:
            - $ref: '#/components/schemas/Error'
            - $ref: '#/components/schemas/TS'
```

**Comment by phrfpeixoto** [comment]
@p1c2u Would you mind reviewing this?

**Comment by p1c2u** [comment]
> It's clear that the result of a usage of an allOf statement should produce an object.

It's said they both compose a single object. Object here is meant by object definition and not object **type**

Take a look at the following example:
```
allOf:
  - type: string
  - type: string
```

**Comment by phrfpeixoto** [comment]
That's exactly what I'm reporting. The code only treats the resulting object as such if you specify the `type`
