### ISSUE TITLE
How to validate against a schema without a request?

### ISSUE THREAD

**Issue by jkupferer** [p1c2u/openapi-core#154]
I am working on using openapi-core to validate Kubernetes resource definitions as described here:

https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definitions/#specifying-a-structural-schema

So far what I have figured out is validating these with a request validator, but I'd like to bypass creating a request if possible because of all the extra steps. Is there a better pattern that I can use to just validate against the schema and avoid the mock request creation?

```
        template_validator = openapi_core.shortcuts.RequestValidator(
            openapi_core.shortcuts.create_spec({
                "openapi": "3.0.0",
                "info": { "title": "", "version": "0.1" },
                "paths": {
                    "/claimTemplate": {
                        "post": {
                            "requestBody": {
                                "required": True,
                                "content": {
                                    "application/json": {
                                        "schema": {
                                            "$ref": "#/components/schemas/ClaimTemplate"
                                        }
                                    }
                                }
                            },
                            "responses": {}
                        }
                    }
                },
                "components": {
                    "schemas": {
                        "ClaimTemplate": openAPIV3Schema
                    }
                }
            })
        )

        validation_result = template_validator.validate(
            openapi_core.wrappers.mock.MockRequest(
                'http://example.com', 'post', '/claimTemplate',
                path_pattern='/claimTemplate',
                data=json.dumps(template)
            )
        )
        validation_result.raise_for_errors()
```

**Comment by p1c2u** [comment]
Hi @jkupferer , check [openapi-spec-validator](https://github.com/p1c2u/openapi-spec-validator) that openapi-core uses to validate schema itself.

**Comment by jkupferer** [comment]
@p1c2u The openapi-spec-validator is only for validating the entire OpenAPI spec definitions, right? What I am trying to do is just validate a YAML or JSON document just using the an OpenAPI schema, just a portion of a full OpenAPI spec, like kubernetes uses in custom resource definitions.

**Comment by p1c2u** [comment]
@jkupferer  I got your point now. To do this you can use Schema factory or registry from schemas submodule. In your example it will be something like the following:
```
from jsonschema.validators import RefResolver
from openapi_spec_validator import default_handlers
from openapi_spec_validator.validators import Dereferencer
from openapi_core.schema.schemas.registries import SchemaRegistry

resolver = RefResolver.from_schema(openAPIV3Schema, handlers=default_handlers)
dereferencer = Dereferencer(resolver)
schema_registry = SchemaRegistry(dereferencer)
schema, _ = schema_registry.get_or_create(openAPIV3Schema)
```

now to validate against the schema:
```
schema.validate(x)
```

**Comment by fleimgruber** [comment]
Could you give a concrete example for `openAPIV3Schema` and `x`?

**Comment by p1c2u** [comment]
I separated schema validation to `openapi-schema-validator` library
https://github.com/p1c2u/openapi-schema-validator

hence closing the issue
