### ISSUE TITLE
Validating nested `items` in array elements types

### ISSUE THREAD

**Issue by dawidgdanski** [p1c2u/openapi-core#155]
Hey,

I encountered one problem I haven't found solution for when using the `openapi-core`:

I developed the schema with an array property:

```
...
errors:
   type: array
          items:
            $ref: '#/components/schemas/ErrorReference'
...
```
I wrote the tests to verify that the `errors` array does contain the `ErrorReference` objects by comparing examplary dictionary against the schema I defined using registered schemas accessible in `Spec.components.schemas`.

When adding nested `items` entry under the existing `items`:
```
...
errors:
   type: array
          items:
               items:
                  $ref: '#/components/schemas/ErrorReference'
...
```
then what I expected was that the upper-level `items` would be inferred with the `array` type, the lower-level `items` with `ErrorReference` type (so that we would have the array of arrays of `ErrorReference`s) and the validation would fail due to the incorrect type found in while validating examplary object dictionary against the schema.

The tests still pass and regardless of how many nested `items` entries are added.

Is it a bug/missing functionality in the validation or am I not using the library correctly to validate nested arrays types?

Many thanks for the response.

**Comment by p1c2u** [comment]
@dawidgdanski thank you for the report.
It's missing functionality which will be added with new validator.
