### ISSUE TITLE
werkzeug is not listed as a dependency

### ISSUE THREAD

**Issue by pbasista** [p1c2u/openapi-core#17]
The `werkzeug` library is not listed as a dependency in:
https://github.com/p1c2u/openapi-core/blob/master/requirements.txt
Not sure if it is intentional, but it seems like a mistake.

**Comment by p1c2u** [comment]
@pbasista the reason is you can use library without using wrappers and `werkzeug` was used as example wrapper implementation.

**Comment by pbasista** [comment]
Ok, I see. But without the `werkzeug` library, it is not possible to import the main `openapi_core` package. The reason is that `__init__` imports `shortcuts`, which then imports `wrappers`. I would argue that if the main package cannot be imported without a certain library, then this library should be made its dependency.

**Comment by p1c2u** [comment]
Yes, you're right, These `__init__` Imports was bad idea.

**Comment by yohanboniface** [comment]
Seems Werkzeug is also a requirement to use the wrappers (for [ImmutableMultiDict](https://github.com/p1c2u/openapi-core/blob/master/openapi_core/wrappers.py#L5)), even without using Flask at all. What about having a basic multidict implementation instead?
