### ISSUE TITLE
create_spec() method taking too much time

### ISSUE THREAD

**Issue by sarangsbabu367** [p1c2u/openapi-core#216]
I am building a large product and in this stage i have an `openapi-spec file with 28000 lines.`
Now i have,

- 53 path objects.

- 14 schema objects.

openapi-core's `create_spec() method is taking around 29 to 34 seconds`. So my server is taking this much time to startup. Is there a remedy for this situation or is this the behaviour of openapi-core's validation ??
ps: So many `Dereferencing` log is present.

**Comment by p1c2u** [comment]
Hi @sarangsbabu367 

I didn't have chance to take closer look at performance topic. Dereferencing suggests you have many references in the spec file Is it correct?

Can you profile `create_spec` function and show the results?

**Comment by sarangsbabu367** [comment]
@p1c2u 
![image](https://user-images.githubusercontent.com/48784283/76620443-2a9f5f00-6553-11ea-91a7-45f9e9f5aec2.png)

**Comment by sarangsbabu367** [comment]
Actually it is a long list, i will upload it as a file.

**Comment by sarangsbabu367** [comment]
It is taking almost 30 secs for validating the schema.

**Comment by p1c2u** [comment]
Can you upload the file so I can see more details?

**Comment by sarangsbabu367** [comment]
> Can you upload the file so I can see more details?

[openapi_core_profile.txt](https://github.com/p1c2u/openapi-core/files/4337334/openapi_core_profile.txt)

**Comment by sarangsbabu367** [comment]
> Can you upload the file so I can see more details?

[openapi_core_profile.txt](https://github.com/p1c2u/openapi-core/files/4338560/openapi_core_profile.txt)

**Comment by sarangsbabu367** [comment]
@p1c2u  The real problem is with loggers in openapi-core. When i disabled these,
```
logging.getLogger("openapi_spec_validator.decorators").setLevel(logging.ERROR)
logging.getLogger("openapi_spec_validator").setLevel(logging.ERROR)
logging.getLogger("openapi_spec_validator.generators").setLevel(logging.ERROR)
logging.getLogger("openapi_spec_validator.validators").setLevel(logging.ERROR)
```
My server starting reduced by 50seconds. I think it will be helpfull to people if you describe this `logging` problem somewhere.
