### ISSUE TITLE
Unable to install openapi-core 0.13.2 with poetry

### ISSUE THREAD

**Issue by sarangsbabu367** [p1c2u/openapi-core#217]
I tried to install openapi-core 0.13.2 with poetry but i got this issue `Could not parse version constraint: >="3.0"` In this issue https://github.com/python-poetry/poetry/issues/2119 they said it is an issue with openapi-core.

**Comment by p1c2u** [comment]
Hi @sarangsbabu367 . Thank you for reporting the issue. It was already reported here #206 and fix is already in master. Hence closing.
