### ISSUE TITLE
Relative servers broken since 0.13.3

### ISSUE THREAD

**Issue by zupo** [p1c2u/openapi-core#218]
We deploy staging on unpredictable URLs (hashes in subdomains) so the `servers` section of our `openapi.yaml` looks like so:

```yaml
servers:
  - url: /api/v1
```

This seems to be valid as per https://swagger.io/docs/specification/api-host-and-base-path/ which lists `/v1/reports` as a valid entry.

However, the latest openapi-core fails with `ServerNotFound: Server not found for http://localhost/api/v1/foo`. The culprit seems to be in how `full_url_pattern` is split into `server_url_pattern`:

```python
(Pdb) l
 68  	                server_url_pattern = full_url_pattern.rsplit(path_result.resolved, 1)[0]
 69  	                server_url = server.get_absolute_url(self.base_url)
 70  	                if server_url.endswith("/"):
 71  	                    server_url = server_url[:-1]
 72  	                # simple path
 73  ->	                if server_url_pattern.startswith(server_url):
 74  	                    server_result = TemplateResult(server.url, {})
 75  	                    yield (path, operation, server, path_result, server_result)
 76  	                # template path
 77  	                else:
 78  	                    result = parse(server.url, server_url_pattern)
(Pdb) server_url_pattern.startswith(server_url)
False
(Pdb) server_url_pattern
'http://localhost/api/v1'
(Pdb) server_url
'/api/v1'
```

**Comment by p1c2u** [comment]
Hi @zupo 

that's correct/expected behavior. You have relative server url (which is allowed by openapi3 spec) but to resolve server you need to pass `base_url`(check line 69) to RequestValidator/ResponseValidator.

**Comment by p1c2u** [comment]
I was thinking, maybe if there is no base_url defined it should validate only relative part of request url. 🤔

**Comment by zupo** [comment]
Makes sense, yes!

I've released a workaround until that is done though, so this issue can be closed.

https://github.com/Pylons/pyramid_openapi3/commit/4e485f1dc2eb1a74488e86faf46c20b6141676cf
