### ISSUE TITLE
Bug in version 0.13.3

### ISSUE THREAD

**Issue by sarangsbabu367** [p1c2u/openapi-core#219]
https://github.com/p1c2u/openapi-core/commit/7e920f829091f78506b99c422414569971e8071e#r37808923

**Comment by p1c2u** [comment]
Hi @sarangsbabu367 

thanks for reporting the bug.

[Request should have path dict](https://github.com/p1c2u/openapi-core/blob/master/openapi_core/validation/request/datatypes.py#L25)

Can you give me more details? Example?

**Comment by sarangsbabu367** [comment]
@p1c2u 
![image](https://user-images.githubusercontent.com/48784283/76682568-38bcb080-6623-11ea-833a-c83f1baf37f1.png)
The problem is in the line which i mentioned above. openapi_core is trying to get path by `request.parameters.path` but path is a key.
![image](https://user-images.githubusercontent.com/48784283/76682624-9cdf7480-6623-11ea-8c59-2913d399075b.png)

**Comment by p1c2u** [comment]
Okay but how your request object look like? How you create request object? Which integration you use?

**Comment by sarangsbabu367** [comment]
I am integrating with starlette.

**Comment by p1c2u** [comment]
The library has no integration with starlette 🤔  You should file a bug to author of the integration library.

**Comment by sarangsbabu367** [comment]
![image](https://user-images.githubusercontent.com/48784283/76931157-0f936d00-690e-11ea-8304-7bdeec2fecd6.png)

I am using openapi_core like this, this works fine with openapi_core version 0.13.2 but got the above exception in version 0.13.3, my request look like this,

![image](https://user-images.githubusercontent.com/48784283/76931282-56816280-690e-11ea-927a-d81bf64c9735.png)

**Comment by p1c2u** [comment]
@sarangsbabu367 
As you can see you use `StarletteOpenAPIRequest` which is not part of the library and the problem must be inside the class.

**Comment by sarangsbabu367** [comment]
@p1c2u Can you please explain how openapi-core wants the request, Previusly i was giving headers, cookies, path, queries as a dictionary inside parameters. Now it is not working, the probem is when i changed this to a `namedtuple` instead of dictionay, I am getting a error `cant set attribute` 
![image](https://user-images.githubusercontent.com/48784283/77400336-fe94a100-6dd0-11ea-96d7-604fcfdff4fb.png)

Line `39` is causing the problem, is it an issue in my side ??

**Comment by sarangsbabu367** [comment]
Issue was with my request structure to openapi_core, when i changed to the format OpenAPIRequest. issue was solved, sorry for wasting your time @p1c2u
