### ISSUE TITLE
Something funky is happening with paths after upgrade from 0.13.1 to 0.13.3

### ISSUE THREAD

**Issue by zupo** [p1c2u/openapi-core#220]
I maintain an example Pyramid app that uses openapi-core under the hood. When [upgrading the library from 0.13.1 to 0.13.3](https://github.com/niteoweb/pyramid-realworld-example-app/pull/97/files) I've encountered a strange bug: responses fail because they don't match schemas of other endpoints. Weird, right? Read on.

In the PR linked above, you can see that I had to move the endpoint definition for `/articles/{slug}/` to a position after endpoint definitions of more specific endpoints, such as `/articles/{slug}/comments`, `/articles/{slug}/comments/{id}` and `/articles/{slug}/favorite`. Otherwise, a valid request to `/articles/{slug}/comments` would fail during response validation with `ValidationError:'article' is a required property`. 

It seems that something changed in how paths are registered and this change now requires that more specific subpaths are now defined *before* less specific paths. I.e. `/item/{id}` needs to be defined *below* `/item/{id}/foo` in `openapi.yaml` file. 

I haven't yet managed to isolate this bug further. @p1c2u do you have any ideas off the top of your head what could cause this?

**Comment by sarangsbabu367** [comment]
@zupo can you check the issue you are facing is #219 , I reported this issue.

**Comment by zupo** [comment]
I don't think these two are the same.

**Comment by p1c2u** [comment]
Hi @zupo 
yeah it must be some problem with [path finder](https://github.com/p1c2u/openapi-core/blob/master/openapi_core/templating/paths/finders.py#L18)

**Comment by svdgraaf** [comment]
Can confirm, having the same issue...

**Comment by p1c2u** [comment]
Prepared test #221 for the use case. Looks like this issue exist inside pyramid integration.

**Comment by zupo** [comment]
Hmm, OK. Let me take another look at it.

**Comment by zupo** [comment]
@svdgraaf: are you using `pyramid_openapi3` or sth. else?

**Comment by svdgraaf** [comment]
I'm generating my own openapi config from AWS ApiGateway, and the order of methods is "random", this works fine on 0.13.1, but on 0.13.3 it started matching the wrong endpoints, eg: `POST /keys/[id]/tokens` was mapped to `POST /tokens`. If I manually switch the methods around in the openapi spec, it works.

I downgraded to 0.13.1 again, and now it works. So something broke in between, haven't looked further yet.

**Comment by p1c2u** [comment]
Now I see the problem. Prepared test for the case.

**Comment by SirEdvin** [comment]
@p1c2u when you will make new release?
