### ISSUE TITLE
HttpProvider does not handle header parameters properly

### ISSUE THREAD

**Issue by stojan-jovic** [p1c2u/openapi-core#234]
My API working with Bearer JWT token and when I tried to enable security validation I found few issues. One is already reported in #223 and I'm glad to see that it's already fixed (thank you for that). Second issue is in the same `HttpProvider` class and refers to the handling of header parameters, specifically `Authorization` header - it's not case insensitive, but it should be, according to the [RFC 2616](https://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html#sec4.2) and [RFC 7230](https://tools.ietf.org/html/rfc7230#appendix-A.2).
And indeed, in my server logic this header field is upper-cased so current HTTP provider implementation raising error for my valid JWT token.

Fix should be pretty simple:
```
headers = {k.lower(): v for k, v in request.parameters.header.items()}
auth_header = headers.get('authorization')
if auth_header is None:
    raise SecurityError('Missing authorization header.')
```

**Comment by p1c2u** [comment]
@stojan-jovic thank you for reporting the issue.

**Comment by stojan-jovic** [comment]
Thank you very much for quick fix, respect!
