### ISSUE TITLE
Documentation does not reflect proper usage of Falcon request and response factories

### ISSUE THREAD

**Issue by stojan-jovic** [p1c2u/openapi-core#240]
In current documentation we have something like this:
```
from openapi_core.contrib.falcon import FalconOpenAPIRequest
from openapi_core.contrib.falcon import FalconOpenAPIResponse
```
But that will not work with current `openapi-core` version (i.e. `0.13.3`).

Solution is probably to add in `openapi_core.contrib.falcon` something like:
```
# backward compatibility
FalconOpenAPIRequest = FalconOpenAPIRequestFactory.create
FalconOpenAPIResponse = FalconOpenAPIResponseFactory.create
```
(so, similar to Flask's factories)

Or simply fix documentation.

**Comment by dlarrick** [comment]
https://github.com/p1c2u/openapi-core/pull/233 fixes the documentation, FYI

**Comment by stojan-jovic** [comment]
Thank you very much!
