### ISSUE TITLE
Submit this library to https://openapi.tools ?

### ISSUE THREAD

**Issue by piotr-dobrogost** [p1c2u/openapi-core#249]
I guess getting this library listed at https://openapi.tools/#data-validators would increase visibility and make Python on par with other languages listed there.

**Comment by p1c2u** [comment]
I agree with you. However I don't know how to submit it. Feel free to do it.

**Comment by jgod** [comment]
It's on the site now, this can be closed

**Comment by p1c2u** [comment]
Thanks guys, hence closing
