### ISSUE TITLE
[Question] Validate response against a specific response schema.

### ISSUE THREAD

**Issue by Booktivity** [p1c2u/openapi-core#272]
Use case: testing. 
In a test I want to check if the response's content matches the schema of the expected status code and not any other schemes defined in the possible responses.

Example:
Let's say you have following example endpoint spec.
```   
 /endpoint:
    get:
        responses:
            '200':
                content:
                    application/json:
                        schema:
                            type: string
            '403':
                content:
                    application/json:
                        schema:
                            type: int
```

Is there a way to validate a response only against the schema specified in '200'? The validation shouldn't try to match the response against the '403' schema.

**Comment by p1c2u** [comment]
Hi @Booktivity 
if you want to validate only schema you should try [openapi-schema-validator](https://github.com/p1c2u/openapi-schema-validator) which is used under the hood

**Comment by Booktivity** [comment]
> Hi @Booktivity if you want to validate only schema you should try [openapi-schema-validator](https://github.com/p1c2u/openapi-schema-validator) which is used under the hood

Thanks and sorry for replying so very late:). IFf openapi-core uses the schema-validator under the hood, then I don't understand why the validator doesn't return validation errors if in my case a django response doesn't match the schema.
