### ISSUE TITLE
Bug: when API endpoint return list, InvalidMediaTypeValue exception was generated

### ISSUE THREAD

**Issue by andyceo** [p1c2u/openapi-core#28]
When some API endpoint return list (array) of something, openapi-core generates `InvalidMediaTypeValue` exception:

	/peers/all
	Request errors: [] Response errors: [InvalidMediaTypeValue('Failed to cast value of [ to SchemaType.OBJECT',)]
	 [FAIL] 1 errors found 
	Response body: [
	]

This exception generated no matter list is empty or not.

**Comment by andyceo** [comment]
Some important addition: it seems that this error is generated only if returned result should be a list of object:

```
  /peers/connected:
	get:
	  summary: Get current connected peers
	  operationId: getConnectedPeers
	  tags:
		- peers
	  responses:
		'200':
		  description: Array of peer objects
		  content:
			application/json:
			  schema:
				type: array
				items:
				  $ref: '#/components/schemas/Peer'
```

In case when list should be list of strings, error did not generated:

```
  /peers/blacklisted:
    get:
      summary: Get blacklisted peers
      operationId: getBlacklistedPeers
      tags:
        - peers
      responses:
        '200':
          description: Array of the addresses
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
                  description: Blacklisted node address
```

**Comment by p1c2u** [comment]
@andyceo of corse, you're right. I forgot that JSON text can be an array too (not just object). I will prepare fix.

**Comment by andyceo** [comment]
Great work! Thank you so much! Can confirm this error is gone. May be new release? :grinning:
