### ISSUE TITLE
Content-Type 	application/json; charset=utf-8

### ISSUE THREAD

**Issue by jitka** [p1c2u/openapi-core#304]
Hi,

our application sends headers with mimetype `'application/json; charset=utf-8'` 
Openapi-core consider this as an error since swagger use just `application/json`.
Could you expand comparison so this would be valid content type?

https://github.com/p1c2u/openapi-core/blob/7a83f019c5c0e592fe72f23ac2c0892d34f9fa02/openapi_core/validation/request/validators.py#L157

I would like to have:
```
minetype = request.mimetype.split(';')[0]
media_type = operation.request_body[mimetype]
```

**Comment by p1c2u** [comment]
Hi @jitka 

which integration you use?
