### ISSUE TITLE
Make sure attributes in request body are in schema

### ISSUE THREAD

**Issue by isdaves** [p1c2u/openapi-core#314]
Hello,

I'm a bit new to this, but I am trying to use the flask decorator version of openapi-core to automatically make flask validate my requests and responses.

However, I found that I can make requests containing extra attributes which do not exist in my schema, and they will be taken in just fine. Is there a way of validating that all the attributes in a request exist in the schema and fail the validation if not?

Example schema:

```
"someSchemaName": {
  "type": "object",
  "properties": {
    "id": {
      "type": "string",
    },
    "attr1": {
      "type": "string",
    },
    "attr2": {
      "type": "string",
  "required": ["id",]
},
```

This POST body will go though validation just fine: `{"id": "1", "foo": "bar"}`

Thanks!

**Comment by p1c2u** [comment]
Hi @isdaves 

please check `additionalProperties` property  for Schema Object in OpenAPI specification

**Comment by isdaves** [comment]
That did the trick, thanks a lot!! 👍
