### ISSUE TITLE
Library does not support optional request body

### ISSUE THREAD

**Issue by stojan-jovic** [p1c2u/openapi-core#324]
So, if we have definition for `requestBody` (e.g. for `POST` request) like this:
```
requestBody:
  content:
    application/json:
      schema:
        $ref: '#/components/schemas/some_json_schema'
  required: false
```
and if we try to make request without body, it will produce error like this:
```
Traceback (most recent call last):
  ...
  File "D:\venvs\.test_venv\lib\site-packages\openapi_core\validation\datatypes.py", line 11, in raise_for_errors
    raise error
  File "D:\venvs\.test_venv\lib\site-packages\openapi_core\validation\request\validators.py", line 164, in _get_body
    deserialised = self._deserialise_media_type(media_type, raw_body)
  File "D:\venvs\.test_venv\lib\site-packages\openapi_core\validation\validators.py", line 28, in _deserialise_media_type
    return deserializer(value)
  File "D:\venvs\.test_venv\lib\site-packages\openapi_core\deserializing\media_types\deserializers.py", line 14, in __call__
    raise DeserializeError(value, self.mimetype)
openapi_core.deserializing.exceptions.DeserializeError: Failed to deserialize value b'' with style application/json
```
even it should allow it because of `required: false`.

**Comment by p1c2u** [comment]
Hi @stojan-jovic thanks for reporting the issue. I will try to fix it today.

**Comment by stojan-jovic** [comment]
Thank you very much for the so quick fix!
Verified it with just released `0.14.2` and it working! Appreciate!

**Comment by stojan-jovic** [comment]
@p1c2u Hm, now we have another issue, when `required: true`, validator will ignore requests without body.

**Comment by stojan-jovic** [comment]
@p1c2u Actually, now validation of request body not working at all... Not sure is that because of this fix, or some of previous releases brought this issue (I updated from `0.13.4`, which worked fine).

**Comment by p1c2u** [comment]
@stojan-jovic interesting. `0.14.0` was a big change. How's your request body definition look like? Can you craft simple test for that?

**Comment by stojan-jovic** [comment]
@p1c2u False alarm, really sorry for that. Everything working fine now! I was looking at wrong swagger spec file while testing first time. Thank you one more time!
