### ISSUE TITLE
additionalProperties support?

### ISSUE THREAD

**Issue by yohanboniface** [p1c2u/openapi-core#33]
Hi,

Not sure if I'm doing something wrong or if `additionalProperties` is missing proper support.

Here is my test case:

```python3
from openapi_core import create_spec
from openapi_core.wrappers import MockRequest, MockResponse
from openapi_core.validators import ResponseValidator


schema = {
    "components": {
        "schemas": {
            "Errors": {
                "additionalProperties": {
                    "type": "string"
                },
                "type": "object"
            }
        }
    },
    "info": {
        "title": "xxx",
        "version": "1.0.0"
    },
    "openapi": "3.0.0",
    "paths": {
        "/simulate": {
            "get": {
                "responses": {
                    "422": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Errors"
                                }
                            }
                        },
                        "description": "Error in data"
                    }
                }
            }
        }
    }
}


spec = create_spec(schema)

validator = ResponseValidator(spec)
request = MockRequest('http://localhost', 'get', '/simulate')
response = MockResponse('{"error_key": "message"}', 422)
result = validator.validate(request, response)
result.raise_for_errors()
```

Which raises the error `openapi_core.exceptions.UndefinedSchemaProperty: Undefined properties in schema: {'error_key'}`.

I'm expecting instead that any key is allowed in the `Error` schema, given I'm using `additionalProperties` (see http://json-schema.org/latest/json-schema-validation.html#rfc.section.6.5.6 and this [discussion](https://github.com/OAI/OpenAPI-Specification/issues/668)).

Thanks for your inputs on this! :)

**Comment by p1c2u** [comment]
@yohanboniface thnks for the bug report. You're right, additionalProperties support is missing atm. I will try to add it shortly.

**Comment by yohanboniface** [comment]
Thanks!

**Comment by yohanboniface** [comment]
@p1c2u one subtle subcase of this: according to the documentation, `additionalProperties` should also accept boolean values, eg.: `additionalProperties: true`, which if I get it right means "additional properties with any type are accepted":

> additionalProperties - Value can be boolean or object. Inline or referenced schema MUST be of a Schema Object and not a standard JSON Schema.

Also, it seems that `additionalProperties: true` should considered as the default starting from OpenAPI 3.0, at least this will be in the documentation starting at 3.0.2, see this change: https://github.com/OAI/OpenAPI-Specification/pull/1548/files. Not sure though if this should be already reflected here or not.

Thanks! :)
