### ISSUE TITLE
Drop support for Python 2.7?

### ISSUE THREAD

**Issue by ashb** [p1c2u/openapi-core#331]
Python 2.7 was now end-of-lifed at the start of this year, and most dists have now moved on to 3.6 or 3.7.

Is it time to drop support for python 2.7 in newer versions of openapi-core?

**Comment by p1c2u** [comment]
Yes, definitely. Dropping support for python < 3.6 is part of release plan.

**Comment by ashb** [comment]
Cool, cos I "broke" 2.7 in my PR to upgrade pytest 😁 

https://github.com/p1c2u/openapi-core/pull/330

For context: I'm investigating replacing connexion with openapi-core in apache/airflow, and I've got a few bugs to fix and I'm seening how actively maintained this project is with these questions and PRs 🙂

**Comment by p1c2u** [comment]
Support dropped hence closing
