### ISSUE TITLE
"oneOf" keyword not supported

### ISSUE THREAD

**Issue by diogobaeder** [p1c2u/openapi-core#37]
Unfortunately this library doesn't support "oneOf", which is fundamental for using flexible/union types. The standard describes this part of the specification, but this library doesn't implement it.

Please let me know if you need help with implementing this.

**Comment by diogobaeder** [comment]
Thanks a lot! :-)

**Comment by diogobaeder** [comment]
Guys, I'm still having issues with `oneOf`; This doesn't work for me, for example:
```yaml
          oneOf:
            - {type: string}
            - {type: integer}
```
and it just throws an error when validating an integer like 22:
```
openapi_core.schema.media_types.exceptions.InvalidMediaTypeValue: Value of 22 not an object
```

**Comment by piotr-dobrogost** [comment]
> and it just throws an error when validating an integer like 22:

I think you are observing bug raised in issue #65 (_oneOf type forced to object_ )

**Comment by diogobaeder** [comment]
Not sure if it's the same; The issues I'm facing with `oneOf` now are related to mixing different primitives and lists of them.

If it is indeed the same, though, then this pull request might fix it: https://github.com/p1c2u/openapi-core/pull/133
