### ISSUE TITLE
Unmarshalling not working properly when the root does not have `type: object`

### ISSUE THREAD

**Issue by Wim-De-Clercq** [p1c2u/openapi-core#401]
Please see https://github.com/p1c2u/openapi-core/commit/3f821484bbcb16b31d9aa0d1a850dbe1e572d062 for a failing testcase.

The docs (https://swagger.io/docs/specification/data-models/oneof-anyof-allof-not/#allof) have examples like 
```yaml
    Dog:     # "Dog" is a value for the pet_type property (the discriminator value)
      allOf: # Combines the main `Pet` schema with `Dog`-specific properties 
        - $ref: '#/components/schemas/Pet'
        - type: object
          # all other properties specific to a `Dog`
          properties:
            bark:
              type: boolean
            breed:
              type: string
              enum: [Dingo, Husky, Retriever, Shepherd]
    Cat:     # "Cat" is a value for the pet_type property (the discriminator value)
      allOf: # Combines the main `Pet` schema with `Cat`-specific properties 
        - $ref: '#/components/schemas/Pet'
        - type: object
          # all other properties specific to a `Cat`
          properties:
            hunts:
              type: boolean
            age:
              type: integer
```
So just a schema with `allOf`, no `type: object`. 
But using such a schema causes some unmarshalling to be skipped, as a date/datetime string would remain a string after `spec_validate_body` instead of being parsed.

When `type: object` is used, (like the comment in the yaml in the commit) then the test case succeeds.

**Comment by p1c2u** [comment]
Unmarshalling mechanism is very simple for now. It determines the type based on top level schema (no allof, anyfo, oneof are taken under consideration)

**Comment by p1c2u** [comment]
This should be resolved with the latest unmarshaller finders refactor
