### ISSUE TITLE
Add integration with Starlette

### ISSUE THREAD

**Issue by sisp** [p1c2u/openapi-core#424]
[Starlette](https://github.com/encode/starlette) is a quite popular ASGI library, in part because it's at the core of the (to me somewhat surprisingly) vastly popular [FastAPI](https://github.com/tiangolo/fastapi) project. Since I believe in the spec-first approach (contrary to FastAPI) and in the architectural design of `openapi-core`, I think it would be great to add an integration with Starlette.

**Comment by p1c2u** [comment]
I was thinking about it. I would go even further and try to integrate with FastAPI itself as an alternative to built-in approach.

**Comment by sisp** [comment]
Hm, I haven't thought about the technical details, but perhaps it's possible to have both because FastAPI is built on top of Starlette? Perhaps via a [Starlette middleware](https://www.starlette.io/middleware/) like it's done for other sane web frameworks. I'm a bit sceptical about FastAPI to be honest. Starlette looks very clean and modular though.

**Comment by sisp** [comment]
Awesome, thanks for adding support for Starlette so quickly, @p1c2u! 🙏 🎉
