### ISSUE TITLE
New Release with Multiple Type Support

### ISSUE THREAD

**Issue by jd014** [p1c2u/openapi-core#438]
Hey @p1c2u,

I have been using this library for awhile with an OpenAPI 3.0.3 spec and am upgrading to 3.1.0. 

While upgrading I noticed that the newest release doesn't support declaring multiple types for a property. However, It looks like the work for this has already been completed in https://github.com/p1c2u/openapi-core/pull/433. 

Could you publish a new minor release with these changes for more complete OpenAPI 3.1 support?

Thanks!

**Comment by p1c2u** [comment]
Hi @jd014 

I'm not very convinced to the current unmarshallers implementation but for the time being it is indeed ready to be released.
