### ISSUE TITLE
Failure to cast or deserialize array of integer query parameters

### ISSUE THREAD

**Issue by wickedest** [p1c2u/openapi-core#439]
The `openapi-core` fails to validate an array of integer query parameters, e.g. : `nums=100&nums=200`, yielding:
```
[DeserializeError('query', 'form', ['100', '200'])]
```
Note that I am using `from urllib.parse import parse_qs`, which will convert those params to:
```
{"nums": ["100","200"]}
```
Perhaps this is not the correct way to provide multiple integers for validation?

In a related matter, the `parse_qs` function decodes _all_ parameter values into an array (even if there is only one value), `parse_qa` will convert one param (singular _num_) to:
```
{"num": ["100"]}
```
However, if the `openapi_request_validator` is given an array for a parameter that isn't an array (i.e. it's just `type: integer`), it will fail to cast:
```
[CastError(value=['100'], type='integer')]
```
It will work if I do not pass an array, i.e. `{"num": "100"}`. I think that `openapi-core` should be able to handle the array of one item as it seems a sensible thing to do.

The code:
```python
import sys
import yaml
from io import StringIO
from urllib.parse import parse_qs
from openapi_core import Spec
from openapi_core.validation.request import openapi_request_validator
from openapi_core.validation.request.datatypes import RequestParameters

class Request:
    method = "get"
    host_url = ""
    path = "/api/v1/banana"
    parameters: RequestParameters
    def __init__(self, query: str):
        self.parameters = RequestParameters(
            parse_qs(query, keep_blank_values=True),
            {},
            {},
            {}
        )
        

openapi_spec = yaml.safe_load(StringIO('''
openapi: 3.1.0
servers:
  - description: Local
    url: /api/v1
info:
  version: 0.1.0
  title: Bug API
  description: Bug
paths:
  /banana:
    get:
      summary: Bug
      parameters:
        - in: query
          name: nums
          explode: false
          schema:
            type: array
            items:
              type: integer
        - in: query
          name: num
          explode: false
          schema:
            type: integer
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema: {}
'''))

def main() -> int:
    print(openapi_spec)
    spec = Spec.create(openapi_spec)
    print(openapi_request_validator.validate(
        spec, Request("num=100")
    ).errors)
    print(openapi_request_validator.validate(
        spec, Request("nums=100&nums=200")
    ).errors)
    return 0

if __name__ == '__main__': 
    sys.exit(main())
```

**Comment by p1c2u** [comment]
Hi @wickedest 
Query (which stores query parameters) in RequestParameters should be type of ImmutableMultiDict. In your case it will be:
```python
from werkzeug.datastructures import ImmutableMultiDict
...
        RequestParameters(
            ImmutableMultiDict(parse_qs(query, keep_blank_values=True)),
            {},
            {},
            {}
        )
```

Another issue I can see  is your `mums` query parameter is `explode: false` which for `form` style expects values list to be define in one parameter with a separator. In your case it should be `nums=100,200` . See [style examples in OpenAPI doc](https://spec.openapis.org/oas/latest.html#style-examples)

**Comment by wickedest** [comment]
Hi @p1c2u - the MultiDict worked. tyvm!
