### ISSUE TITLE
Plans for openapi-schema-validator 0.4 support?

### ISSUE THREAD

**Issue by musicinmybrain** [p1c2u/openapi-core#456]
Since `openapi-schema-validator` is [now at 0.4.0](https://github.com/p1c2u/openapi-schema-validator/releases/tag/0.4.0), are you planning to keep the dependency pinned to `^0.3.0` here and in `openapi-spec-validator` for some time, or are you planning an updated release that supports the current version of `openapi-schema-validator`?

https://github.com/p1c2u/openapi-core/blob/6d8f1d962ec61bc077fcd8113d695100fc49dd6f/pyproject.toml#L62

**Comment by p1c2u** [comment]
Hi @musicinmybrain  yes, there's no reason to keep it pinned to 0.3.x. Thanks for pointing this out.

**Comment by musicinmybrain** [comment]
Thanks for looking at this!
