### ISSUE TITLE
Wheel package of 0.5.0 on pypi.org contains extra files

### ISSUE THREAD

**Issue by pbasista** [p1c2u/openapi-core#47]
[This](https://files.pythonhosted.org/packages/0a/ac/415e02427f1adcb725bf061af32dca794ca45a6d5a8c2c0e77bee0b3d6fd/openapi_core-0.5.0-py3-none-any.whl) wheel package of version `0.5.0` hosted on [pypi.org](https://pypi.org/project/openapi-core/) contains extra files when compared to a wheel package generated locally from git tag `0.5.0` using `python setup.py bdist_wheel` command in a clean virtual environment. The full diff is [here](https://github.com/p1c2u/openapi-core/files/2122825/openapi-core.wheels.diff.txt).

The extra files, for instance `openapi_core/validators.py`, were present in the repository before PR #25 was merged. They are present in the wheel package of `0.5.0`, but not in the source package of `0.5.0`.

This probably indicates an issue with generating the wheel packages, where the files from previously generated wheel packages are somehow included in the new wheel package as well. I think it should be investigated and resolved.

**Comment by domenkozar** [comment]
@p1c2u could the wheel be deleted? It's causing issues with testing:

```
>   from openapi_core.wrappers.base import BaseOpenAPIRequest, BaseOpenAPIResponse
E   ModuleNotFoundError: No module named 'openapi_core.wrappers.base'; 'openapi_core.wrappers' is not a package
```

Since pytest imports `wrappers.py` first instead of `wrappers/` package.

**Comment by p1c2u** [comment]
@pbasista @domenkozar
0.5.0 was unfortunate version. I hope 0.6.0 will be much better. Thank you for your help. Cheers.
