### ISSUE TITLE
Minimum and maximum properties are not validated

### ISSUE THREAD

**Issue by jonpoveda** [p1c2u/openapi-core#49]
**Version:** 0.5.0

**Expected result:** setting a number below 'minimum' or above 'maximum' properties on an should add an error in the attribute `RequestValidationResult.errors` when `RequestValidator.validate` is called.

**Actual result:** Specifying the parameters 'minimum' or 'maximum' makes no difference when validating, returning a `None` when `RequestValidationResult.errors` is checked.

**Comment by pbasista** [comment]
The relevant part of the code:
https://github.com/p1c2u/openapi-core/blob/master/openapi_core/schema/schemas/factories.py#L16

The OpenAPI [schema properties](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.1.md#properties), which are currently not supported:
* `multipleOf`
* `maximum`
* `exclusiveMaximum`
* `minimum`
* `exclusiveMinimum`
* `maxLength`
* `minLength`
* `pattern`
* `maxItems`
* `minItems`
* `uniqueItems`
* `maxProperties`
* `minProperties`

Their definition can be obtained from:
https://tools.ietf.org/html/draft-wright-json-schema-validation-00#section-5
