### ISSUE TITLE
Uncustomizable type casting

### ISSUE THREAD

**Issue by muzhig** [p1c2u/openapi-core#53]
Currently the Schema class does automatic type casting, for string it doesn't do even that.
Which actually could be not the desired behavior: some might need to force strict type match for example, just like me. I solved the problem currently by monkey-patching DEFAULT_CAST_CALLABLE_GETTER. 
Does it sound reasonable to make this customizable?

**Comment by p1c2u** [comment]
@muzhig Hi. Can you provide simple example?

**Comment by muzhig** [comment]
```
    @classmethod
    def set_strict_type_casting(cls):
        def force_type(*types):
            def type_caster(value):
                if not isinstance(value, types):
                    raise ValueError(value)
                return value

            return type_caster

        cls.DEFAULT_CAST_CALLABLE_GETTER.update({
            SchemaType.BOOLEAN: force_type(bool),
            SchemaType.INTEGER: force_type(int),
            SchemaType.NUMBER: force_type(int, float),
            SchemaType.STRING: force_type(str),
        })
```
this way it will allow to force types to exactly match the schema

**Comment by p1c2u** [comment]
@muzhig thanks for the example now I see your point.  You want to skip value casting for schema. I think optional argument should do the trick.
