### ISSUE TITLE
dataclasses (attrs) instead of free form data structure

### ISSUE THREAD

**Issue by domenkozar** [p1c2u/openapi-core#88]
For validated data structures, it would provide a lof of value if those were also assured throughout the python codebase. For example if field renames or changes type, one should get an error before runtime.

Essentially could write an inverse of https://pypi.org/project/dataclasses-jsonschema/, but I haven't looked how hard that is.

**Comment by p1c2u** [comment]
Dataclasses are supported in python 3.6 and 3.7 only and openapi-core support 2.7-3.7. It's impossible to make it builtin. However it will be possible to provide dataclasses with model factory option which is work in progress.

**Comment by domenkozar** [comment]
Using attrs in some of my PRs.

**Comment by zupo** [comment]
> However it will be possible to provide dataclasses with model factory option which is work in progress.

Could you share some more details on model factories? Is there an issue that tracks the idea/progress?
